service: websocket
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  versionFunctions: false
  stage: "dev"
  region: eu-central-1
  httpApi:
    cors: true
  websocketsApiName: websockets-api
  websocketsApiRouteSelectionExpression: $request.body.action

functions:
  OnConnectHandler:
    handler: app/handler.handler
    events:
      - websocket:
          route: $connect
  OnDisconnect:
    handler: app/handler.handler
    events:
      - websocket:
          route: $disconnect
  OnBroadcast:
    handler: app/handler.handler
    events:
      - websocket:
          route: $message

plugins:
  - serverless-offline
  - serverless-plugin-typescript

custom:
  dynamodb:
    start:
      migrate: true

resources:
  Resources:
    WebSocketTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Customers
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
